// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5-DSCD9D-zHxCIotIs_ca_nbZqayxebA',
    appId: '1:961987906678:web:e6afc53f8924f514c12357',
    messagingSenderId: '961987906678',
    projectId: 'flutterfirst-1a5e1',
    authDomain: 'flutterfirst-1a5e1.firebaseapp.com',
    storageBucket: 'flutterfirst-1a5e1.firebasestorage.app',
    measurementId: 'G-PJQGLRFN3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvmLNQJQj37eH6J0Yw0RtpL_U1arR7QDo',
    appId: '1:961987906678:android:466ebffa81c556cec12357',
    messagingSenderId: '961987906678',
    projectId: 'flutterfirst-1a5e1',
    storageBucket: 'flutterfirst-1a5e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGrFlmhkA-LnN2hFeh7JT8LlkbXptPn5E',
    appId: '1:961987906678:ios:e9038d0aab39ec7dc12357',
    messagingSenderId: '961987906678',
    projectId: 'flutterfirst-1a5e1',
    storageBucket: 'flutterfirst-1a5e1.firebasestorage.app',
    iosBundleId: 'com.example.firstflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGrFlmhkA-LnN2hFeh7JT8LlkbXptPn5E',
    appId: '1:961987906678:ios:e9038d0aab39ec7dc12357',
    messagingSenderId: '961987906678',
    projectId: 'flutterfirst-1a5e1',
    storageBucket: 'flutterfirst-1a5e1.firebasestorage.app',
    iosBundleId: 'com.example.firstflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5-DSCD9D-zHxCIotIs_ca_nbZqayxebA',
    appId: '1:961987906678:web:056805312b1d8aa5c12357',
    messagingSenderId: '961987906678',
    projectId: 'flutterfirst-1a5e1',
    authDomain: 'flutterfirst-1a5e1.firebaseapp.com',
    storageBucket: 'flutterfirst-1a5e1.firebasestorage.app',
    measurementId: 'G-0Y26T24E4H',
  );

}